### ISSUE TITLE
Multiple errors when trying out some methods

### ISSUE THREAD

**Issue by Giugiur** [cryptoplease/cryptoplease-dart#103]
Hey guys, I'm trying out the package and I'm new at Solana, so I wonder what I'm doing wrong.

Right out of the box, the examples copy pasted from GitHub on the example folder are not working for me. I'm even trying other methods but get errors on your package.

For instance on:
```
await source.createAssociatedTokenAccount(mint: _tokenMint);
```
I get 
> Error: jsonrpc-2.0 error (-32602): Invalid param: not a v2.0 Token mint

This is taken directly from the [list provided](https://github.com/solana-labs/token-list/blob/main/src/tokens/solana.tokenlist.json). Then if I change the token mint to SOL it changes the error message to:
> Error: Expected a value of type 'int', but got one of type 'double'

Note that I'm not using any kind of _double_ value. Similar examples with other methods can be found, it always breaks at some line in the package. Also, somewhat related (or not) _requestAirdrop_ takes a lot of time to complete whereas on the CLI it takes only a second.

Anyway, I'm at a loss on how to solve any of these issues. Maybe you guys know what I'm missing?

**Comment by iharobCP** [comment]
Hi @Giugiur. Can you please share which token you tried and on which network? Thanks. The second error is strange, but it will probably be fixed in our next release coming soon.

**Comment by Giugiur** [comment]
Sure, the first one I tried was on the devnet, the token was USDT provided in the example on the repo:
> Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB

I switched to SOL:
> So11111111111111111111111111111111111111112

And then I got the second error message.

Thanks for your quick response btw.

**Comment by iharobCP** [comment]
Hi. Thank you for clarifying. The `Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB` is USDT indeed but on the mainnet. You need to check the `"chainId"` field from the [token list](https://github.com/solana-labs/token-list/blob/main/src/tokens/solana.tokenlist.json) file. Also, the `So11111111111111111111111111111111111111112` is actually correct for _Wrapped SOL_ so that is indeed a bug that we are creating an issue for immediately. However, as I mentioned before, there is a good chance that this will be resolved in the next release.

**Comment by Giugiur** [comment]
Weird, since it was on the example you guys provided in the repo. Do you have a target date for the next release?

**Comment by antoineherzog** [comment]
This PR needs to be reviewed carefully after the Solana Breakpoint conference:
https://github.com/cryptoplease/cryptoplease-dart/pull/93
So we are expecting mid november.

**Comment by antoineherzog** [comment]
One more thing, the best way to understand the library is to read our test suite:
https://github.com/cryptoplease/cryptoplease-dart/tree/master/packages/solana/test

**Comment by Giugiur** [comment]
Gotcha, thanks for the answers. I will look at the test suite then since I was basing only on the examples.
