### ISSUE TITLE
How do I send NFT

### ISSUE THREAD

**Issue by TransFormes** [cryptoplease/cryptoplease-dart#111]
I have some NFT, how do I send it

**Comment by antoineherzog** [comment]
Check this issue for help
https://github.com/cryptoplease/cryptoplease-dart/issues/109

**Comment by TransFormes** [comment]
Thank you for your reply. I have found the method, but it is not this issue. Now I want to get the details of NFT, how to use Borsh deserialization? Are there any examples

**Comment by trienbaoha** [comment]
@TransFormes Do you have a solution?
