### ISSUE TITLE
Is there a problem sending spl tokens? I get an error -WrongSize- when a try to call SplToken.readOnly

### ISSUE THREAD

**Issue by ArjLab** [cryptoplease/cryptoplease-dart#116]

**Comment by iharobCP** [comment]
Hi. Can you please share the code that reproduces it please?

**Comment by ArjLab** [comment]
mint: Fp4gjLpTsPqBN6xDGpDHwtnuEofjyiZKxxZxzvJnjxV6
rpcClient: RPCClient('https://api.mainnet-beta.solana.com');

**Comment by ArjLab** [comment]
@iharobCP await SplToken.readonly(mint: mintAddress, rpcClient: rpcClientMainnet);
