### ISSUE TITLE
Discussion about ParsedAccountData implementation

### ISSUE THREAD

**Issue by ChikinDeveloper** [cryptoplease/cryptoplease-dart#121]
Hello, currently we have this :

```dart
ParsedAccountData _$ParsedAccountDataFromJson(Map<String, dynamic> json) {
  switch (json['program'] as String?) {
    case 'spl-token':
      return SplTokenProgramAccountData.fromJson(json);
    case 'stake':
      return StakeProgramAccountData.fromJson(json);

    default:
      return UnsupportedProgramAccountData.fromJson(json);
  }
}
```

There is an issue when trying to extract a token mint account : Since the program is spl-token too, this will try to unpack it into a TokenAccount which is wrong.

I think jsonParsed account data should always be extracted into a unique class (the equivalent of UnsupportedProgramAccountData). Users can always use SplTokenProgramAccountData.fromJson(json) on their own when they need too.

**Comment by antoineherzog** [comment]
@ChikinDeveloper Please check master! All the changed has been push to master. Any other feedback is welcome! Closing the issue now
