### ISSUE TITLE
Will token swap instructions? 

### ISSUE THREAD

**Issue by ArjLab** [cryptoplease/cryptoplease-dart#128]

**Comment by iharobCP** [comment]
Not particularly soon. You can always build your own set of instructions. Take a look at the `token_program.dart` and `toke_instruction.dart` as a guideline.

**Comment by TransFormes** [comment]
If there's a simple example, I don't know where to start

**Comment by ArjLab** [comment]
@TransFormes  I'm working on it right now

**Comment by TransFormes** [comment]
> @TransFormes 我现在正在处理
Thank you for your efforts. I will do the swap function now. Could you help me

**Comment by TransFormes** [comment]
@ArjLab Thank you for your efforts. I will do the swap function now. Could you help me

**Comment by ArjLab** [comment]
@TransFormes Send it here. If I can't help, someone will answer

**Comment by TransFormes** [comment]
@ArjLab 
I still don’t know where to start, I’m watching orca sdk, but it can’t be used in flutter,  [https://github.com/orca-so/typescript-sdk](url)

**Comment by ArjLab** [comment]
@TransFormes If I am not mistaken this library should be enough to write your own swap instructions that will work through the pool. @iharobCP @ookami-kb @Syaba999 
Correct me if I'm wrong

**Comment by ArjLab** [comment]
@TransFormes I wrote a small server on dart for swap. But it works without the pool. You send it seed phrase, address of token A, token B and amount. The server exchanges token A for token B. But it works without the pool. The usual exchanger

**Comment by TransFormes** [comment]
@ArjLab Can I take a look at the code, thank you very much

**Comment by iharobCP** [comment]
> @TransFormes If I am not mistaken this library should be enough to write your own swap instructions that will work through the pool. @iharobCP @ookami-kb @Syaba999 Correct me if I'm wrong

You are correct. We are currently working on porting some of [these programs](https://github.com/cryptoplease/cryptoplease-dart/issues/91). We think of adding the swap program afterwards. Unless of course @ArjLab you share your implementation with us.

**Comment by ArjLab** [comment]
@TransFormes 

class SwapInstruction extends Instruction {
  SwapInstruction._({
    required String programId,
    required List<AccountMeta> accounts,
    required Iterable<int> data,
  }) : super(
          programId: programId,
          accounts: accounts,
          data: data,
        );

  static const swapTokenInstructionIndex = [9];

  factory SwapInstruction.swap(
   {required String programId,
  // amm
  required String ammId,
  required String ammAuthority,
  required String ammOpenOrders,
  required String ammTargetOrders,
  required String poolCoinTokenAccount,
  required String poolPcTokenAccount,
  // serum
  required String serumProgramId,
  required String serumMarket,
  required String serumBids,
  required String serumAsks,
  required String serumEventQueue,
  required String serumCoinVaultAccount,
  required String serumPcVaultAccount,
  required String serumVaultSigner,
  // user
  required String userSourceTokenAccount,
  required String userDestTokenAccount,
  required String userOwner,

  required int amountIn,
  required int minAmountOut}
  ) => SwapInstruction._(
      accounts: [
        AccountMeta.readonly(pubKey: TokenProgram.programId, isSigner: false),

        AccountMeta.writeable(pubKey: ammId, isSigner: false),
        AccountMeta.readonly(pubKey: ammAuthority, isSigner: false),

        AccountMeta.writeable(pubKey: ammOpenOrders, isSigner: false),
        AccountMeta.writeable(pubKey: ammTargetOrders, isSigner: false),
        AccountMeta.writeable(pubKey: poolCoinTokenAccount, isSigner: false),
        AccountMeta.writeable(pubKey: poolPcTokenAccount, isSigner: false),

        AccountMeta.readonly(pubKey: serumProgramId, isSigner: false),
        AccountMeta.writeable(pubKey: serumMarket, isSigner: false),

        AccountMeta.writeable(pubKey: serumBids, isSigner: false),
        AccountMeta.writeable(pubKey: serumAsks, isSigner: false),
        AccountMeta.writeable(pubKey: serumEventQueue, isSigner: false),
        AccountMeta.writeable(pubKey: serumCoinVaultAccount, isSigner: false),
        AccountMeta.writeable(pubKey: serumPcVaultAccount, isSigner: false),
        AccountMeta.readonly(pubKey: serumVaultSigner, isSigner: false),
        AccountMeta.writeable(pubKey: userSourceTokenAccount, isSigner: false),
        AccountMeta.writeable(pubKey: userDestTokenAccount, isSigner: false),
        AccountMeta.readonly(pubKey: userOwner, isSigner: true),
      ],
      data: Buffer.fromConcatenatedByteArrays([
        swapTokenInstructionIndex,
        Buffer.fromUint64(amountIn),
        Buffer.fromUint64(minAmountOut)
    ]).toList(),
      programId: programId,
    );
}

**Comment by ArjLab** [comment]
@TransFormes  This works for exchange on Raydium

`class SwapInstruction extends Instruction {
  SwapInstruction._({
    required String programId,
    required List<AccountMeta> accounts,
    required Iterable<int> data,
  }) : super(
          programId: programId,
          accounts: accounts,
          data: data,
        );

  static const swapTokenInstructionIndex = [9];

  factory SwapInstruction.swap(
   {required String programId,
  // amm
  required String ammId,
  required String ammAuthority,
  required String ammOpenOrders,
  required String ammTargetOrders,
  required String poolCoinTokenAccount,
  required String poolPcTokenAccount,
  // serum
  required String serumProgramId,
  required String serumMarket,
  required String serumBids,
  required String serumAsks,
  required String serumEventQueue,
  required String serumCoinVaultAccount,
  required String serumPcVaultAccount,
  required String serumVaultSigner,
  // user
  required String userSourceTokenAccount,
  required String userDestTokenAccount,
  required String userOwner,

  required int amountIn,
  required int minAmountOut}
  ) => SwapInstruction._(
      accounts: [
        AccountMeta.readonly(pubKey: TokenProgram.programId, isSigner: false),

        AccountMeta.writeable(pubKey: ammId, isSigner: false),
        AccountMeta.readonly(pubKey: ammAuthority, isSigner: false),

        AccountMeta.writeable(pubKey: ammOpenOrders, isSigner: false),
        AccountMeta.writeable(pubKey: ammTargetOrders, isSigner: false),
        AccountMeta.writeable(pubKey: poolCoinTokenAccount, isSigner: false),
        AccountMeta.writeable(pubKey: poolPcTokenAccount, isSigner: false),

        AccountMeta.readonly(pubKey: serumProgramId, isSigner: false),
        AccountMeta.writeable(pubKey: serumMarket, isSigner: false),

        AccountMeta.writeable(pubKey: serumBids, isSigner: false),
        AccountMeta.writeable(pubKey: serumAsks, isSigner: false),
        AccountMeta.writeable(pubKey: serumEventQueue, isSigner: false),
        AccountMeta.writeable(pubKey: serumCoinVaultAccount, isSigner: false),
        AccountMeta.writeable(pubKey: serumPcVaultAccount, isSigner: false),
        AccountMeta.readonly(pubKey: serumVaultSigner, isSigner: false),
        AccountMeta.writeable(pubKey: userSourceTokenAccount, isSigner: false),
        AccountMeta.writeable(pubKey: userDestTokenAccount, isSigner: false),
        AccountMeta.readonly(pubKey: userOwner, isSigner: true),
      ],
      data: Buffer.fromConcatenatedByteArrays([
        swapTokenInstructionIndex,
        Buffer.fromUint64(amountIn),
        Buffer.fromUint64(minAmountOut)
    ]).toList(),
      programId: programId,
    );
}`

**Comment by ArjLab** [comment]
@TransFormes  This works for exchange on Raydium

    import 'package:solana/solana.dart';
    
    class SwapInstruction extends Instruction {
      SwapInstruction._({
        required String programId,
        required List<AccountMeta> accounts,
        required Iterable<int> data,
      }) : super(
              programId: programId,
              accounts: accounts,
              data: data,
            );
    
      static const swapTokenInstructionIndex = [9];
    
      factory SwapInstruction.swap(
       {required String programId,
      // amm
      required String ammId,
      required String ammAuthority,
      required String ammOpenOrders,
      required String ammTargetOrders,
      required String poolCoinTokenAccount,
      required String poolPcTokenAccount,
      // serum
      required String serumProgramId,
      required String serumMarket,
      required String serumBids,
      required String serumAsks,
      required String serumEventQueue,
      required String serumCoinVaultAccount,
      required String serumPcVaultAccount,
      required String serumVaultSigner,
      // user
      required String userSourceTokenAccount,
      required String userDestTokenAccount,
      required String userOwner,
    
      required int amountIn,
      required int minAmountOut}
      ) => SwapInstruction._(
      accounts: [
        AccountMeta.readonly(pubKey: TokenProgram.programId, isSigner: false),

        AccountMeta.writeable(pubKey: ammId, isSigner: false),
        AccountMeta.readonly(pubKey: ammAuthority, isSigner: false),

        AccountMeta.writeable(pubKey: ammOpenOrders, isSigner: false),
        AccountMeta.writeable(pubKey: ammTargetOrders, isSigner: false),
        AccountMeta.writeable(pubKey: poolCoinTokenAccount, isSigner: false),
        AccountMeta.writeable(pubKey: poolPcTokenAccount, isSigner: false),

        AccountMeta.readonly(pubKey: serumProgramId, isSigner: false),
        AccountMeta.writeable(pubKey: serumMarket, isSigner: false),

        AccountMeta.writeable(pubKey: serumBids, isSigner: false),
        AccountMeta.writeable(pubKey: serumAsks, isSigner: false),
        AccountMeta.writeable(pubKey: serumEventQueue, isSigner: false),
        AccountMeta.writeable(pubKey: serumCoinVaultAccount, isSigner: false),
        AccountMeta.writeable(pubKey: serumPcVaultAccount, isSigner: false),
        AccountMeta.readonly(pubKey: serumVaultSigner, isSigner: false),
        AccountMeta.writeable(pubKey: userSourceTokenAccount, isSigner: false),
        AccountMeta.writeable(pubKey: userDestTokenAccount, isSigner: false),
        AccountMeta.readonly(pubKey: userOwner, isSigner: true),
      ],
      data: Buffer.fromConcatenatedByteArrays([
        swapTokenInstructionIndex,
        Buffer.fromUint64(amountIn),
        Buffer.fromUint64(minAmountOut)
    ]).toList(),
      programId: programId,
          );
      }

**Comment by iharobCP** [comment]
Hi @ArjLab. Could you please create a PR to include this in the library? Please follow the structure in the `programs/` directory. Otherwise if it is ok with you, could I borrow this and create it myself? Also, how many instructions are there in this program?

**Comment by ArjLab** [comment]
@@iharobCP Hi. Yes, of course. You implement it faster and better. I don't know how many instructions are in this program. I'm still learning it

**Comment by Syaba999** [comment]
> @TransFormes If I am not mistaken this library should be enough to write your own swap instructions that will work through the pool. @iharobCP @ookami-kb @Syaba999 Correct me if I'm wrong

Hi. Yes, this library is enough to implement swap. We implemented swap using the Token Swap Program and Raydium.

**Comment by ritvij14** [comment]
Hi @Syaba999 I am also trying to work on a flutter app for token swap, I am confused as to how am I supposed to write the "program" part of this. Like if we take a look in the code for Token Program, it has 2 files, one for the program and one for the instruction
https://github.com/cryptoplease/cryptoplease-dart/tree/master/packages/solana/lib/src/programs/token_program

So in our case, where is the program for token swap and how should I be using it? And can I write the same in dart itself?

Apologies if my questions are a bit too basic, I am still new to Solana and figuring out things. 😅

**Comment by InFaMoUsZero** [comment]
> 

Thanks for this, very useful. Can you please post a simple example of this code in use?

**Comment by ritvij14** [comment]
Was going through this issue once again to read the instructions mentioned, @iharobCP did you try implementing the swap instructions on your end? Were you able to create a sample code for it?

**Comment by ritvij14** [comment]
[instruction code](https://github.com/ritvij14/solana_token_swap_flutter/blob/main/lib/token_swap_instruction.dart)
[program code](https://github.com/ritvij14/solana_token_swap_flutter/blob/main/lib/token_swap_implementation.dart)
[implementation function](https://github.com/ritvij14/solana_token_swap_flutter/blob/main/lib/token_swap_implementation.dart)

I tried implementing token swap in a flutter app but couldn't succeed. Current issue I am facing is this:
```
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
```

Even tho I am airdropping sol into the swap account.
