### ISSUE TITLE
When the HTTP request times out, no timeout process is performed

### ISSUE THREAD

**Issue by TransFormes** [cryptoplease/cryptoplease-dart#134]

**Comment by TransFormes** [comment]
waitForSignatureStatus The method timeout is 30, and I often timeout when I use it

**Comment by antoineherzog** [comment]
Thank you for posting an issue! We will have a look. 
In the meantime, we are currently refactoring the subscription client to handle better to subscribe to signature status here
https://github.com/cryptoplease/cryptoplease-dart/pull/133

**Comment by antoineherzog** [comment]
It will not happen with the last version
