### ISSUE TITLE
Add OnChain Metadata  decoder account for NFT (SPL token with 0 decimal)

### ISSUE THREAD

**Issue by antoineherzog** [cryptoplease/cryptoplease-dart#139]
cf.
https://docs.phantom.app/integrating/tokens/on-chain-metadata

**Comment by ludowkm** [comment]
@iharobCP do you have any ideas for the current issue?

**Comment by ludowkm** [comment]
hi @antoineherzog, is this issue solved yet?

**Comment by antoineherzog** [comment]
Yes it is going to be soon :)

**Comment by ludowkm** [comment]
Yes, hope to have it soon, i tried to decode to get URI but not success

**Comment by ludowkm** [comment]
hi @antoineherzog , @iharobCP , is there any news about it?
To achieve this one, we need to make like metaplex.
Referal: https://gist.github.com/dvcrn/c099c9b5a095ffe4ddb6481c22cde5f4

**Comment by antoineherzog** [comment]
@iharobCP Iharob is drafting a PR soon :)

**Comment by antoineherzog** [comment]
https://github.com/cryptoplease/cryptoplease-dart/pull/163
