### ISSUE TITLE
EVM format key

### ISSUE THREAD

**Issue by AcikgozMuharrem** [cryptoplease/cryptoplease-dart#141]
Hi everyone,

I have been developing my own mobile app wallet. The native keys are something like this in base58encode format 7uuiRsMum3eDegkusqbkeGb1LPV4cvk5q4tyV7YvTzxt

How Can I "convert" it to ether format which starts with 0x?

Here is my case actually;
When I import my own created private key to MetaMask it derives a pubkey/address an ether format pubkey. 
I only get the balance with the native keys in my mobile app, not with the pubkeys which are ether format. So I should "convert" native pubkey/adddress to ether format?

I hope it is clear

Is there anyone tried to do it, thanks very much.

Regards,

Muharrem

**Comment by iharobCP** [comment]
I am not sure how this would work, but you have the raw bytes of the public key using `base58decode` and then I guess you can encode the way you need.

**Comment by AcikgozMuharrem** [comment]
Yes, I do have the raw bytes of the public key the way you mentioned. I should find out the rest, thanks @iharobCP
