### ISSUE TITLE
How to decode encoded AccountData (jsonParsed or base64) ?

### ISSUE THREAD

**Issue by Yusuf-Uluc** [cryptoplease/cryptoplease-dart#148]
I want to decode my `AccountData` which is encoded as `base64` or `jsonParsed` (I don't really care which one) but can't find out how to do it.

**Comment by iharobCP** [comment]
Account data is decoded by the library. Please read this [https://docs.solana.com/developing/clients/jsonrpc-api#getprogramaccounts](JSON RPC API | Solana) for more information about your use case. If it is a custom program then you will have to use `base64`. The `jsonParsed` encoding only works for a few account types mostly from the native programs.
