### ISSUE TITLE
Get Mnemonic from Wallet/Ed25519HDKeyPair

### ISSUE THREAD

**Issue by tapizquent** [cryptoplease/cryptoplease-dart#159]
Is there any way to get a Mnemonic phrase when generating a Wallet for the first time?

**Comment by ookami-kb** [comment]
If you have already generated the Wallet, there's no way to get a mnemonic phrase from it.

If you need to generate a wallet, it's usually the other way around – first, you generate a mnemonic phrase (e.g. using [this method](https://pub.dev/documentation/bip39/latest/bip39/generateMnemonic.html) from `bip39` library), and then create a wallet from this mnemonic using [fromMnemonic](https://pub.dev/documentation/solana/latest/solana/Ed25519HDKeyPair/fromMnemonic.html) method.
