### ISSUE TITLE
Current progress of this library.

### ISSUE THREAD

**Issue by InFaMoUsZero** [cryptoplease/cryptoplease-dart#169]
Hi, great work with the library!

Just a quick question, what is the current state or feature set of this library?

I see in another issue a comment saying it's was quite complete now? Can anyone elaborate on what is supported and what is not?

**Comment by antoineherzog** [comment]
@iharob will get back to you soon but you can use for any kind of use-case on Solana.
We are launching a crypto wallet Crypto Please with the last version (0.18) : https://www.cryptoplease.com
