### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by EPNW** [cryptoplease/cryptoplease-dart#170]
Hi,

I found the solana package on pub.dev, but pub.dev shows no web support for the solana package, although all its depencencies are supported on web (according to pub.dev). This means that the package itself uses either `dart:ffi` or `dart:io` imports. Reading the code I could not find any `dart:ffi` code, but a single line of `dart:io` code in [stake_program.dart](https://github.com/cryptoplease/cryptoplease-dart/blob/8e6335ee3bc448725b3286dead215acfc81853ac/packages/solana/lib/src/programs/stake_program/stake_program.dart#L213):

```dart
    lockupAuthorityPubKey: HttpHeaders.locationHeader,
```

If the value of `HttpHeaders.locationHeader` (which is just the string `location`) would be hardcoded here, the `dart:io` import could be removed, and the code should be able to run on the web.

Could you do that and remove that import for the published package? The http header should be standardized anyway so it should not change in the future 😅 . I'd really like to give the package a try on the web 😄

**Comment by antoineherzog** [comment]
the package is already used on the web by some developers So you can give it a try :)
Yes @iharob will look into this issue tomorrow.
