### ISSUE TITLE
Not able to delegate a stake.

### ISSUE THREAD

**Issue by dsk7990** [cryptoplease/cryptoplease-dart#171]
First of all, thanks for these excellent package. 
I am facing issue when i want to delegate a stake. 

Getting below response from the api.
**ERROR:**
`{accounts: null, err: {InstructionError: [0, InvalidAccountOwner]}, logs: [Program Stake11111111111111111111111111111111111111 invoke [1], Program Stake11111111111111111111111111111111111111 failed: Invalid account owner]}`

**CODE:**

`final ownerKey = keyPair;`
`final stakeAccountKey = await Ed25519HDKeyPair.random();`
```
final message = StakeProgram.createAccount(
      fromPubKey: ownerKey.address,
      stakePubKey: stakeAccountKey.address,
      authorized: Authorized(
        staker: ownerKey.address,
        withdrawer: ownerKey.address,
      ),
      lamports: amountToStake.toInt(),
    );
```
```
String sign = await rpc
        .signAndSendTransaction(message, [
      ownerKey,
      stakeAccountKey,
    ]);
```
```
final delegateMessage= StakeProgram.delegateStake(
        stakePubKey: stakeAccountKey.address,
        votePubKey: 'DNTc4P9ngY51Uc8hXSjhJdZdLTxyx7j1N1GbfXjVkLPr',
        configPubKey: 'StakeConfig11111111111111111111111111111111',
        authorityPubKey: ownerKey.address);
```
  ```
String delegateSign= await rpc
        .signAndSendTransaction(delegateMessage, [ownerKey]);
```

Awaiting for your response.

**Comment by Nithsua** [comment]
I wasn't able to recreate your issue I think it's an issue with your account also isn't delegateStake still Unimplemented

**Comment by iharob** [comment]
> I wasn't able to recreate your issue I think it's an issue with your account also isn't delegateStake still Unimplemented

What do you mean unimplemented?

**Comment by iharob** [comment]
> First of all, thanks for these excellent package. I am facing issue when i want to delegate a stake.
> 
> Getting below response from the api. **ERROR:** `{accounts: null, err: {InstructionError: [0, InvalidAccountOwner]}, logs: [Program Stake11111111111111111111111111111111111111 invoke [1], Program Stake11111111111111111111111111111111111111 failed: Invalid account owner]}`
> 
> **CODE:**
> 
> `final ownerKey = keyPair;` `final stakeAccountKey = await Ed25519HDKeyPair.random();`
> 
> ```
> final message = StakeProgram.createAccount(
>       fromPubKey: ownerKey.address,
>       stakePubKey: stakeAccountKey.address,
>       authorized: Authorized(
>         staker: ownerKey.address,
>         withdrawer: ownerKey.address,
>       ),
>       lamports: amountToStake.toInt(),
>     );
> ```
> 
> ```
> String sign = await rpc
>         .signAndSendTransaction(message, [
>       ownerKey,
>       stakeAccountKey,
>     ]);
> ```
> 
> ```
> final delegateMessage= StakeProgram.delegateStake(
>         stakePubKey: stakeAccountKey.address,
>         votePubKey: 'DNTc4P9ngY51Uc8hXSjhJdZdLTxyx7j1N1GbfXjVkLPr',
>         configPubKey: 'StakeConfig11111111111111111111111111111111',
>         authorityPubKey: ownerKey.address);
> ```
> 
> ```
> String delegateSign= await rpc
>       .signAndSendTransaction(delegateMessage, [ownerKey]);
> ```
> 
> Awaiting for your response.

How did you create your stake account?

**Comment by Nithsua** [comment]
> > I wasn't able to recreate your issue I think it's an issue with your account also isn't delegateStake still Unimplemented
> 
> What do you mean unimplemented?

delegateStake constructor throws unimplemented error

` factory StakeProgram.delegateStake({
    required String stakePubKey,
    required String votePubKey,
    required String configPubKey,
    required String authorityPubKey,
  }) =>
      throw UnimplementedError();`

**Comment by dsk7990** [comment]
> 

I haven't created any stake account.

**Comment by Nithsua** [comment]
@antoineherzog If any help is needed would love to contribute

**Comment by antoineherzog** [comment]
@Nithsua Crypto Please wrote you on Twitter. Check your DM!

**Comment by iharobCP** [comment]
> > 
> 
> @iharob I haven't created any stake account.

You have to create a stake account. You can do it within a single message. The error message is saying that you attempted to stake using a non-stake account. The account owner is not the stake program. Please refer to the rust sdk to see an example [here](https://github.com/solana-labs/solana/blob/master/sdk/program/src/stake/instruction.rs#L439) to see an example of how to do it, translating this idea should be simple.

**Comment by dsk7990** [comment]
> **CODE:**
> 
> `final ownerKey = keyPair;` `final stakeAccountKey = await Ed25519HDKeyPair.random();`

I have created stake account, please refer above code. Are you talking about the same or something else?

FYI: Through the given code, i am able to create an account and even stake has also Initialized but not able to delegate. I am also referring the example which you have provided in previous comment,

**Comment by dsk7990** [comment]
> You have to create a stake account. You can do it within a single message. The error message is saying that you attempted to stake using a non-stake account. The account owner is not the stake program. Please refer to the rust sdk to see an example [here](https://github.com/solana-labs/solana/blob/master/sdk/program/src/stake/instruction.rs#L439) to see an example of how to do it, translating this idea should be simple.

@iharob with the help of your given example i have resolved the issue. Thank you for your quick help.
