### ISSUE TITLE
createWallet should run in isolate

### ISSUE THREAD

**Issue by ookami-kb** [cryptoplease/cryptoplease-dart#18]
Currently, `createWallet` is asynchronous but blocking. It should run heavy operations in isolate instead,

**Comment by Syaba999** [comment]
> Currently, `createWallet` is asynchronous but blocking. It should run heavy operations in isolate instead,

Could you tell me where this function is? We cannot find it in the source code

**Comment by ookami-kb** [comment]
Yeah, the code was updated since the time, it's now `SolanaWallet.fromMnemonic`, but it's still not running in an isolate.

**Comment by antoineherzog** [comment]
@ookami-kb is this still relevant?

**Comment by ookami-kb** [comment]
Yes

**Comment by antoineherzog** [comment]
I am going to create a ticket now

**Comment by antoineherzog** [comment]
Ok i added it to the board

**Comment by ArjLab** [comment]
Run a separate isolate for createWallet?

**Comment by ookami-kb** [comment]
Actually, it looks like it was resolved as part of #35 – at least, I don't see any heavy operations blocking the isolate atm.

So closing this, and feel free to create a new issue if there will be some problems with performance, we'll take a look.
