### ISSUE TITLE
Solana Devnet Without Webscoket how do I transfer SOL

### ISSUE THREAD

**Issue by TransFormes** [cryptoplease/cryptoplease-dart#183]

**Comment by ookami-kb** [comment]
If you don't need WS, you can just use [RpcClient](https://github.com/cryptoplease/cryptoplease-dart/blob/master/packages/solana/lib/src/rpc/client.dart) directly.

**Comment by ookami-kb** [comment]
Closing the issue. Feel free to open a new one or join our new [Solana Dart developers](https://discord.gg/TF2FWKCQ) Discord server.
