### ISSUE TITLE
Wallet Integration Solana

### ISSUE THREAD

**Issue by tapizquent** [cryptoplease/cryptoplease-dart#186]
This package is great as it contains a way to call the RPC client.

Is there any way to integrate with Solana wallets such as Phantom?

**Comment by antoineherzog** [comment]
We've just created a discord channel:
https://discord.gg/28h8KCF2

**Comment by jackbbhua** [comment]
discord link had expired.can you send a new one?

**Comment by ookami-kb** [comment]
@jackbbhua can you try one in the readme please? It should be a non-expiring link.
