### ISSUE TITLE
'Null' is not a subtype of type 'String' in type cast - getClusterNodes()

### ISSUE THREAD

**Issue by HickYeah** [cryptoplease/cryptoplease-dart#191]
During my testing to this lib, I noticed the following error when I call getClusterNodes()

`[ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast`

seems like we need better handling of the following file 

ClusterNode _$ClusterNodeFromJson(Map<String, dynamic> json) => ClusterNode(
      pubkey: json['pubkey'] as String,
      gossip: json['gossip'] as String,
      tpu: json['tpu'] as String,   <<<. _CastError (type 'Null' is not a subtype of type 'String' in type cast)
      rpc: json['rpc'] as String?,
      version: json['version'] as String?,
      featureSet: json['featureSet'] as int?,
      shredVersion: json['shredVersion'] as int?,
    );

Let me know what you think?

**Comment by antoineherzog** [comment]
You can join our discord here
https://discord.gg/28h8KCF2
