### ISSUE TITLE
Import secret key

### ISSUE THREAD

**Issue by themou3ad** [cryptoplease/cryptoplease-dart#195]
Hello i'm having an issue importing a new wallet with a secret key that i got from a phantom wallet:

i tried using this: 
  final key = await base58.decode(secretKey);
  keyPair = await Ed25519HDKeyPair.fromPrivateKeyBytes(privateKey: key);
  
and i got this : Exception: SigningKey must be created from a 32 byte seed

is the base58 decoding suitable for this ?

the secret key is : "3FNpNeFC5dRg1bRAqn7Y9eWgmuwzzgnLzia6uv7xHxmTyrPNx5L4trSHSWyJp91BUhnZKotyLoKwVkfdjmbkjX2w"

i know it's not good to share secret keys like this....but it's for testing only. 

Thanks a lot !

**Comment by ookami-kb** [comment]
AFAIK, Phantom wallet actually exports key pair rather than just private key, try this instead:

```dart
final key = await base58.decode(secretKey);
keyPair = await Ed25519HDKeyPair.fromPrivateKeyBytes(privateKey: key.take(32).toList());
```

**Comment by themou3ad** [comment]
Nice ! it works nicely
