### ISSUE TITLE
Is it possible to add a merchant payments option? 

### ISSUE THREAD

**Issue by dinarpay** [cryptoplease/cryptoplease-dart#212]
Hello
Is it possible to add a merchant payments option? 
Solana Pay
https://github.com/fyfylabs/fyfy-mobile-wallet/blob/master/lib/pages/pay.dart

Thanks

**Comment by ookami-kb** [comment]
Hi,

Paying with Solana Pay is already supported:

Send -> By scanning QR code -> scan Solana Pay QR code.

**Comment by daniarmas** [comment]
> Hi,
> 
> Paying with Solana Pay is already supported:
> 
> Send -> By scanning QR code -> scan Solana Pay QR code.

Hi but in the case of a mobile application how would it be ?

**Comment by antoineherzog** [comment]
I don't understand your question?

**Comment by daniarmas** [comment]
> I don't understand your question?

ok I am not an expert on the subject, keep this in mind.

![mobile-app-mobile-wallet-flow-a4f6de9056f2b9a4fe50e0878d68c4d9 (1)](https://user-images.githubusercontent.com/66922462/161097065-d0b399b0-7ad9-488c-b795-d50e8f7d2ee9.png)

"Payment requests could be encoded as a deep link. The app prepares a payment request, and passes control to the wallet. The wallet signs, sends, and confirms it, or cancels the request and passes control back to the app."

This is from the solana pay doc. The part I don't understand is how I am going to make a payment request to the wallet from my mobile app. In the case of a web it is through the QR that scans the wallet that is well detailed in the doc of solana pay but in this case the doc says that by deep linking but there is nothing documented.

**Comment by antoineherzog** [comment]
We are building this feature right now. Come back in 1 or 2 weeks, you will see!

**Comment by daniarmas** [comment]
> We are building this feature right now. Come back in 1 or 2 weeks, you will see!

waoo awesome, thank you very much for the work.
