### ISSUE TITLE
I want to build a wallet

### ISSUE THREAD

**Issue by dinarpay** [cryptoplease/cryptoplease-dart#229]
Hello
I want to build a wallet
Celo blockchain network
To be used in daily dispatch and payment transactions
No transaction fees 
Notification system like Trustwallet
Example of a celo wallet 
https://github.com/bi23com/CeloDance

**Comment by ookami-kb** [comment]
Hi,

Sorry, I don't understand, what exactly your question is.

**Comment by dinarpay** [comment]
I want a mobile application for Celo network
Android and iOS app

Found this app
https://github.com/bi23com/CeloDance
But your application is fast and simple, but it only works with Solana Network

**Comment by ookami-kb** [comment]
Yes, our app currently only works with Solana Network, we're not going to add support for other networks in the near future.
