### ISSUE TITLE
getTokenLargestAccounts parsing error when querying an NFT mint

### ISSUE THREAD

**Issue by mugveiga** [cryptoplease/cryptoplease-dart#269]
**Describe the bug**
If you need to query the current holder of an NFT.. you should use `getTokenLargestAccounts`
but this is using ProgramAccount as return type.. and it fails to parse the output.

```
Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
    #0      _$ProgramAccountFromJson (package:solana/src/rpc/dto/program_account.g.dart:11:49)
    #1      new ProgramAccount.fromJson (package:solana/src/rpc/dto/program_account.dart:15:7)
    #2      _RpcClient.getTokenLargestAccounts.<anonymous closure> (package:solana/src/rpc/client.rpc.dart:752:39)
```

**To Reproduce**
call getTokenLargestAccounts with an NFT address.

**Expected behavior**
the largest accounts of that NFT mint so we can figure out who is the current owner.

**Comment by ookami-kb** [comment]
Thank you! Fixed in `0.23.0+1`.
