### ISSUE TITLE
TimeoutException after 0:00:30.000000: Future not completed

### ISSUE THREAD

**Issue by sunsetjesus** [cryptoplease/cryptoplease-dart#273]
**createAssociatedTokenAccount future timesout**

**To Reproduce**
```
await _solanaClient.createAssociatedTokenAccount(
          owner: keyPair.publicKey, mint: mintPubKey, funder: keyPair);
```

**Expected behavior**
Future gets resolved
**Additional context**
rpc url - https://api.devnet.solana.com
solana: ^0.23.0+1
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Dart 2.16.2

**Comment by ookami-kb** [comment]
You can create a `SolanaClient` with a custom timeout value. Try to use some bigger value if it works for you.
