### ISSUE TITLE
TimeoutException after 0:00:30.000000: Future not completed exception on transferSplToken yet tokens get deducted

### ISSUE THREAD

**Issue by sunsetjesus** [cryptoplease/cryptoplease-dart#274]
**Future Times out yet tokens get deducted**

**To Reproduce**
```
      await _solanaClient.transferSplToken(
          mint: mintPubKey,
          destination: destinationPubKey,
          amount: amount,
          owner: keyPair,
          commitment: Commitment.processed,
          });
```

**Expected behavior**
return signature 
**Additional context**
rpc url - https://api.devnet.solana.com/
solana: ^0.23.0+1
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Dart 2.16.2

**Comment by ookami-kb** [comment]
You can create a `SolanaClient` with a custom timeout value. Try to use some bigger value if it works for you.

**Comment by ookami-kb** [comment]
I see that you're using `commitment: Commitment.processed`. It's not supported by this method, try using `confirmed` or `finalized`.
