### ISSUE TITLE
Flutter Web: TypeError: core.BigInt.from is not a function when calling SolanaClient createAssociatedTokenAccount

### ISSUE THREAD

**Issue by rflawn** [cryptoplease/cryptoplease-dart#282]
Using the latest library version : solana: ^0.24.0+1

Flutter web on Chrome Version 102.0.5005.61 (Official Build) (x86_64)

Error message: TypeError: core.BigInt.from is not a function

Flutter Code snippet: 

  SolanaClient createTestSolanaClient() => SolanaClient(
    rpcUrl: Uri.parse(devnetRpcUrl),
    websocketUrl: Uri.parse(devnetWebsocketUrl),
  );

  solanaClient = createTestSolanaClient();

  owner = await Ed25519HDKeyPair.random();

    final token = await solanaClient.initializeMint(
      mintAuthority: owner,
      decimals: 2,
    );

   newToken = token;

  final account = await Ed25519HDKeyPair.random();

  var tAccount = await solanaClient.createTokenAccount(
    account: account,
    creator: owner,
    mint: newToken.address,
  );

accounts = await solanaClient.rpcClient.getTokenAccountsByOwner(
    owner.address,
    TokenAccountsFilter.byMint(newToken.address.toBase58()),
    encoding: Encoding.jsonParsed,
  );

  var tokenMinted = await solanaClient.mintTo(
    destination: Ed25519HDPublicKey.fromBase58(accounts.first.pubkey),
    amount: _totalSupply,
    mint: newToken.address,
    authority: owner,
  );

final TokenAmount tokenSupply = await solanaClient.rpcClient
      .getTokenSupply(newToken.address.toBase58());

  final recipient = await Ed25519HDKeyPair.random();

****_// throws error here_**** TypeError: core.BigInt.from is not a function
  final associatedAccount = await solanaClient.createAssociatedTokenAccount(
    owner: recipient.publicKey,
    funder: owner,
    mint: token.address,
  );

**Comment by ookami-kb** [comment]
I couldn't reproduce this issue. If you can still reproduce it, please add more details and reopen the issue.
