### ISSUE TITLE
Need a BU1 to be able to serialize boolean (smallest is u8 today)

### ISSUE THREAD

**Issue by thomnico** [cryptoplease/cryptoplease-dart#289]
**Describe the bug**
I want to have booleans representations in my solana prog (true/false) and did not find a way to use borsh to serialize it, hence need to use BU8 which is more costly. Would appreciate a BU1 or BBool type to achieve this.
Thoughts?

**Expected behavior**
a borsh serialize type for booleans with examples and code generation.

**Comment by ookami-kb** [comment]
[Borsh specification](https://borsh.io/#pills-specification) doesn't provide any guides on bool serialization/deserialization, so we can't include it in Dart implementation.

Also, borsh serializes objects to a set of bytes, so byte (or u8) is the minimal item anyway.

**Comment by thomnico** [comment]
Thanks
