### ISSUE TITLE
Error: Type 'Uint8List' not found in Solana package 0.25.0

### ISSUE THREAD

**Issue by thomnico** [cryptoplease/cryptoplease-dart#310]
**Describe the bug**
In Solana package 0.25.0 not present in 0.24.0

When trying to use it I got the following error:
/opt/homebrew/Caskroom/flutter/3.0.4/flutter/.pub-cache/hosted/pub.dartlang.org/solana-0.25.0/lib/src/rpc/dto/account_data/binary_account_data.dart:6:9: Error: Type 'Uint8List' not found.
  final Uint8List data;

        ^^^^^^^^^
/opt/homebrew/Caskroom/flutter/3.0.4/flutter/.pub-cache/hosted/pub.dartlang.org/solana-0.25.0/lib/src/rpc/dto/account_data/binary_account_data.dart:6:9: Error: 'Uint8List' isn't a type.
  final Uint8List data;

        ^^^^^^^^^

**To Reproduce**
1. Try to use solana package and Binary_account_data

**Comment by ookami-kb** [comment]
Not reproducible.

**Comment by thomnico** [comment]
0.26 is not showing the same issue so all good for me
