### ISSUE TITLE
design improvement of the request/pay page

### ISSUE THREAD

**Issue by antoineherzog** [cryptoplease/cryptoplease-dart#354]
![16 (1)](https://user-images.githubusercontent.com/13095/183646521-c5414647-3c71-4663-9ed4-1a6e7531301b.png)

**Comment by moksh-mahajan** [comment]
Hi @antoineherzog 
Where can I find the details about the improvements we want to make here?

**Comment by antoineherzog** [comment]
Hey @moksh-mahajan 
Nice to meet you,
Ricardo is already working on it! If you want to help the project, please DM on twitter we can chat:
https://twitter.com/cryptopleasecom

**Comment by moksh-mahajan** [comment]
Hi @antoineherzog 
Twitter DM is not available for @cryptopleasecom

**Comment by antoineherzog** [comment]
try again
