### ISSUE TITLE
Issue in link generation process for sending money

### ISSUE THREAD

**Issue by moksh-mahajan** [cryptoplease/cryptoplease-dart#364]
**Describe the bug**
I was trying out the send money using the link feature. After the link generation process got completed, the first link was blank and the **"SHARE PAYMENT LINKS"** link button was also disabled. 
Also when I go to the 'Activities' tab and click on that shareable link item then also it shows the same state: first link being blank and **"SHARE PAYMENT LINKS"** button being disabled.

**To Reproduce**
1. Go to the home tab
2. Tap on **Send** Button
3. Tap on **With a link** button
4. Enter the amount in sol
5. Click on **Next** button
6. After the link generation process only the second link is visible and share button is also disable

**Expected behavior**
After the above 5 steps and after the link generation process, both link should be visible while the share button not being disabled.

**Screenshots**
![Screenshot_20220813-1422472](https://user-images.githubusercontent.com/36201975/184517443-2e4c6557-e1ec-48ab-b4d1-88a75fdf667e.png)

**Smartphone**
 - Device: Pixel 4a
 - OS: Android 12
 - Version: 1.39.0 (115)

**Additional context**
I'm not sure if this bug is reproducible each time. I only tried it one time and encountered this issue.

**Comment by ookami-kb** [comment]
Hi @moksh-mahajan,

Can you please check if the issue is resolved now? You can try the same payment from the "Activities" tab, it should generate the link.

**Comment by moksh-mahajan** [comment]
Nope @ookami-kb!
The same screen got displayed. Plus I was using the playstore version (1.39.0). Now I built and ran the app from the master branch. Re-imported my old wallet but the "Activities" tab is showing - "No Activities".

Were they being stored locally and now lost forever?

**Comment by moksh-mahajan** [comment]
Getting this error: 
`Unhandled Exception: [firebase_dynamic_links/unknown] com.google.android.gms.common.api.ApiException: 403: Requests from this Android client application com.pleasecrypto.flutter are blocked.`

I think it's because I have not added my SHA keys to the firebase project.

**Comment by ookami-kb** [comment]
Yes, the activities are only stored locally.

The error for the local dev environment is expected because your SHA keys are not added to the firebase project, you're right on that. But I was fixing it for the production signature, I will check it again.

**Comment by ookami-kb** [comment]
Updated, it should be working in production now.
