### ISSUE TITLE
No padding at the bottom of "Select token" list

### ISSUE THREAD

**Issue by ookami-kb** [cryptoplease/cryptoplease-dart#389]
**Describe the bug**

**To Reproduce**

1. Go to Swap page
2. Click on source token selector
3. Scroll down to the bottom

**Expected behavior**

Add padding.

**Screenshots**

<img src="https://user-images.githubusercontent.com/853356/186992941-29ac3230-d810-448f-9b3d-10cc98aa6cb6.png" width="300">

**Smartphone:**
 - Device: iPhone13
 - OS: iOS15.2
 - master branch

**Comment by moksh-mahajan** [comment]
Working on the fix @ookami-kb
