### ISSUE TITLE
Destination token doesn't change automatically

### ISSUE THREAD

**Issue by ookami-kb** [cryptoplease/cryptoplease-dart#390]
**Describe the bug**

When you select source token the same as destination token, destination token is not updated automatically.

**To Reproduce**
1. Go to Swap page.
2. Click on source token.
3. Select the same token as destination token.
4. See error.

**Expected behavior**

Destination token should be automatically updated after source token is changed.

**Screenshots**

<img src="https://user-images.githubusercontent.com/853356/186993481-fff4f708-7164-4896-b783-e1c1c91e9ac6.png" width="300">

**Smartphone:**
 - Device: iPhone13
 - OS: iOS15.2
 - master branch

**Comment by moksh-mahajan** [comment]
@ookami-kb I would like to work on this one.

**Comment by moksh-mahajan** [comment]
@ookami-kb After selecting the source token the same as the destination token, what should the destination token be updated to?

**Comment by ookami-kb** [comment]
@moksh-mahajan I would say it should work like this in general:

- if you select the source token the same as the destination token, the destination token should be updated to the previously selected source token if it's available in the updated paths;
- if you change the source token, the destination token should stay the same if it's available in the updated paths;
- otherwise, destination token falls back to the default selection (IIRC, the first of the popular ones, then the first available).

**Comment by moksh-mahajan** [comment]
@ookami-kb I think I have covered all these pointers in the updated PR. Could you please take a look and let me know if there are any changes required?

**Comment by ookami-kb** [comment]
Sure, will take a look, thanks!
