### ISSUE TITLE
When I'm calling sendTransaction method not getting signature.

### ISSUE THREAD

**Issue by parth22** [cryptoplease/cryptoplease-dart#428]
I'm swapping tokens by using Jupiter swap for Solana. And, It's working fine I'm getting swapped serialized transactions for a particular route. But after that when I'm trying to get a signature by using these serialized transactions received by Jupiter swap. I'm using sendTransaction method of the Solana flutter package at that time I'm getting the below error logs.

```Error Logs:
Program logic: Instruction: Set Token Ledger
Program log: AnchorError caused by account: token_account. Error Code: AccountNotInitialized. Error Number: 3012. Error Message: The program expected this account to be already initialized.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. I'm calling Jupiter v1/quote
2. After that I'm calling Jupiter v1/swap
3. than Using the below method to get a signature.

```  
Future<String?> maybeExecuteTx({
    required String? tx,
    required ValueSetter<SwapException> onError,
  }) async {
    try {
      if (tx == null) return null;

      final decoded = base64Decode(tx);
      final byteArray = ByteArray(decoded);
      final compiled = CompiledMessage.fromSignedTransaction(byteArray);
      final message = Message.decompile(compiled);
      final recent = await client.rpcClient.getRecentBlockhash();
      final recompiled = message.compile(recentBlockhash: recent.blockhash);
      final walletDetails = wallet;

      final signedTx = SignedTx(
          messageBytes: recompiled.data,
          signatures: [await walletDetails.sign(recompiled.data)]);

      final transaction = signedTx.encode();

      final signature = await client.rpcClient.sendTransaction(
        transaction,
        preflightCommitment: Commitment.confirmed,
      );
      await client.waitForSignatureStatus(
        signature,
        status: Commitment.confirmed,
        timeout: const Duration(minutes: 1),
      );

      return signature;
    } on SwapException catch (e) {
      onError(e);
    }
    return null;
  }
```
  
4. See an error I attached a screenshot of it.
<img width="725" alt="Screenshot 2022-09-13 at 6 37 04 PM" src="https://user-images.githubusercontent.com/13308845/190075850-e1aa4cfc-aea5-408c-bfa1-6479f10789ed.png">

**Expected behaviour**
As expected behaviour, I will get a signature for this transaction.

Thanks

**Comment by parth22** [comment]
Hi, guys any updates on this issue?

**Comment by rhbrunetto** [comment]
Can you post the complete log for this error? It's hard to extract info on the screenshot.

**Comment by parth22** [comment]
This was a transaction sequence issue. @rhbrunetto I have solved it.
