### ISSUE TITLE
cryptography's sha256.hash fails for flutter web when accessed in android app webview

### ISSUE THREAD

**Issue by ChikinDeveloper** [cryptoplease/cryptoplease-dart#45]
### How to reproduce

* Deploy a flutter web app
* Access it within a webview, for example : MathWallet's dapp webview
* Call findProgramAddress
Should fail

### Our (temporary) solution

* Use sha256 from crypto package instead of cryptography, it works

**Comment by antoineherzog** [comment]
Thank you for your ticket! 

We are focus on mobile development right now. We will probably not fix at the moment as it is not our top priority. Otherwise you can submit a PR.

Have a good day!
