### ISSUE TITLE
HTTP dependency update

### ISSUE THREAD

**Issue by bradyAdger12** [cryptoplease/cryptoplease-dart#51]
Would you mind upgrading to the latest 'http' version (^0.13.3). Whenever I try to downgrade my http version, it causes incompatibility with most of my other very common dependencies.

**Comment by iharobCP** [comment]
Hello @bradyAdger12. Please feel free to create a PR, we'd be happy to merge it.

**Comment by bradyAdger12** [comment]
My mistake. I was looking at this plugin https://pub.dev/packages/solana_dart. The Github link took me to this repo. I'm now seeing the correct dependency I'm supposed to be using. Thanks!
