### ISSUE TITLE
Send SPL token. Other fee payer

### ISSUE THREAD

**Issue by ArjLab** [cryptoplease/cryptoplease-dart#54]

**Comment by antoineherzog** [comment]
@iharob is there an example with an other fee payer?

**Comment by ArjLab** [comment]
No. 
Please add an example of how to send spl token with another commission payer.
Thank.

**Comment by ArjLab** [comment]
> No.
> Please add an example of how to send spl token with another commission payer.
> Thank.

[https://ibb.co/xFTP6vQ](url)
return error 'index out of bounds'

**Comment by ArjLab** [comment]
> > No.
> > Please add an example of how to send spl token with another commission payer.
> > Thank.

https://ibb.co/xFTP6vQ
return error 'index out of bounds'

**Comment by antoineherzog** [comment]
@iharob can you please add an example of sending a SPL token with another fee payer

**Comment by iharobCP** [comment]
Hello. I created a PR adding an example and a test. The idea is basically to build the message via `TokenProgram.transfer` and then provide 1 extra signer (must be the first in the list) when signing and sending the transaction.

In the future, we will provide _feePayer_ as a parameter to convenience methods of which we already have some.

@ArjLab @antoineherzog  :point_up:

**Comment by ArjLab** [comment]
Thank you @iharobCP
