### ISSUE TITLE
error {accounts: null, err: {InstructionError: [0, {Custom: 1}]}

### ISSUE THREAD

**Issue by ArjLab** [cryptoplease/cryptoplease-dart#71]
var wallet = Wallet(
      signer: await Ed25519HDKeyPair.fromMnemonic(seed),
      rpcClient: rpcClient,
    );
var funder = Wallet(
        signer: await Ed25519HDKeyPair.fromMnemonic(_seedFee),
        rpcClient: rpcClient);
    wallet.createAssociatedTokenAccount(mint: _mint, funder: funder);

>> return error 
{accounts: null, err: {InstructionError: [0, {Custom: 1}]}, logs: [Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1], Program log: Transfer 2039280 lamports to the associated token account, Program 11111111111111111111111111111111 invoke [2], Transfer: insufficient lamports 453526, need 2039280, Program 11111111111111111111111111111111 failed: custom program error: 0x1, Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 200000 of 200000 compute units, Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL failed: custom program error: 0x1]}

**Comment by ArjLab** [comment]
add example for function 'createAssociatedTokenAccount'

**Comment by antoineherzog** [comment]
@iharob can you check?

**Comment by ArjLab** [comment]
and?

**Comment by iharobCP** [comment]
Hello @ArjLab. We are going to provide this example soon. We found this problem already and it will be resolved in our next release this Friday.

**Comment by ArjLab** [comment]
Thank you guys
