### ISSUE TITLE
when we receive a payment with links or tips, pre-updated the homepage so the balance is already up to date (no need to pull to refresh))

### ISSUE THREAD

**Issue by antoineherzog** [cryptoplease/cryptoplease-dart#735]
when we receive a payment with links or tips, pre-updated the homepage so the balance is already up to date (no need to pull to refresh))

**Comment by rhbrunetto** [comment]
Also, we need to add auto-refresh balance after buy/selling a token.

**Comment by antoineherzog** [comment]
Yep!
