### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iharobCP** [cryptoplease/cryptoplease-dart#82]
Some of the documentation is already generated.

**Comment by tyirenkyi** [comment]
Hello @iharobCP, I would love to take up this. Could you give me more information?

**Comment by iharobCP** [comment]
Hi @tyirenkyi. Thank you. We are almost ready with a new release which will have a fairly complete documentation. This release will also include full support for the RPC api. We are expecting to release it this week.

**Comment by tyirenkyi** [comment]
Great!
I'm a little confused 😅. Do you need help with documentation or do you have it figured out for this new release?

**Comment by iharobCP** [comment]
Sorry if I didn't make myself clear. I meant that we did take care of it as a consequence of some other work we're doing.
