### ISSUE TITLE
Example for Minting NFT as per Metaplex Standard

### ISSUE THREAD

**Issue by Sharaddition** [cryptoplease/cryptoplease-dart#94]
Please include an example of how we can mint an NFT as per the [Metaplex Token Metadata Standard](https://docs.metaplex.com/nft-standard). Also include how to pass an array of multiple token creators with different royalties.

**Comment by tapizquent** [comment]
Hello @iharob . Have any of the examples been implemented yet?
I don't see a single example in the repo that will point me in the right direction to build with this client
